site_name: NOMAD Tutorial Workflows
site_url: https://fairmat-nfdi.github.io/nomad-tutorial-workflows
repo_url: https://github.com/FAIRmat-NFDI/nomad-tutorial-workflows
site_description: |
  A tutorial demonstrating workflow and project management in NOMAD
site_author: FAIRmat consortium
nav:
  - Overview: index.md
  - Part 1 - Core Functionalities: core.md
  - Part 2 - Python API: api.md
  - Part 3 - Custom Entries: custom.md
  - Part 4 - Workflows: workflows.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      # primary: '#2A4CDF'
      # accent: '#008A67'
      scheme: default
      # toggle:
        # icon: material/weather-sunny
        # name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      # toggle:
        # icon: material/weather-night
        # name: Switch to light mode
  font:
    text: 'Titillium Web'
  logo: assets/nomad-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - versioning
    - content.buttons
  prev_next_buttons_location: both


  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - bibtex:
      bib_file: docs/assets/refs.bib
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: True
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js'
  - 'https://unpkg.com/cytoscape@3.19.1/dist/cytoscape.min.js'
  - 'assets/custom.js'
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

  # - assets/code/parse.js
extra:
  version:
    provider: mike
  generator: false

